---
- hosts: localhost
  gather_facts: yes
  vars:
    verbose: true
  pre_tasks:
    - block:
        - setup:
      rescue:
        - name: "Install required python-minimal package"
          raw: "apt-get update && apt-get install -y --force-yes python-apt python-minimal"
        - setup:
  become: yes

  roles:
    - update
    - default_packages
    - desktop_packages
    - backup
    - upgrade
