---

- name: Install VIM package
  apt: name=vim state=latest

- name: Install Sysinfo package
  apt: name=sysinfo state=latest

- name: Install Command-not-found package
  apt: name=command-not-found state=latest

- name: Install ntp package
  apt: name=ntp state=latest
